export const BFF_REDIS_CONFIG = {
  REFRESH_LOCK_TTL_MS: 5000,
  REFRESH_RESULT_TTL_MS: 10000,
  REFRESH_WAIT_TIMEOUT_MS: 5500,
  REFRESH_POLL_INTERVAL_MS: 80,
  REFRESH_POLL_JITTER_MS: 30,
} as const;
