/**
 * NOTE: DURATION holdMs 동기화 관련 변경
 * - DURATION_MATCH_THRESHOLD를 @repo/stretching-accuracy에서 import하여 사용
 * - SUCCESS_ACCURACY_THRESHOLD: 60 → DURATION_MATCH_THRESHOLD 상수 참조로 변경
 * - 참고: py-reference/accuracy.py의 DURATION_MATCH_THRESHOLD와 동일 값 사용
 */
import { DURATION_MATCH_THRESHOLD } from '@repo/stretching-accuracy';

export const STRETCHING_SESSION_CONFIG = {
  // 미디어파이프 세팅
  MODEL_ASSET_PATH: '/models/pose_landmarker_lite.task',
  WASM_ROOT: 'https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/wasm',

  // 캔버스 어떻게 보여주는지 mode (video | keypoints | video-keypoints | silhouette)
  VISUALIZATION_MODE: 'silhouette' as const,

  // 키포인트 렌더러 옵션들 (video-keypoints, keypoints 모드에만 사용)
  KEYPOINTS_LINE_COLOR: '#00FF00',
  KEYPOINTS_LINE_WIDTH: 2,
  KEYPOINTS_POINT_COLOR: '#FF0000',
  KEYPOINTS_POINT_RADIUS: 3,
  KEYPOINTS_BACKGROUND_COLOR: '#000000',
  KEYPOINTS_VISIBILITY_THRESHOLD: 0.5,
  KEYPOINTS_SHOW_POINTS: true,

  // 실루엣 모드일 때 세팅값
  SILHOUETTE_FOREGROUND_RGBA: { r: 107, g: 114, b: 128, a: 255 },
  SILHOUETTE_BACKGROUND_RGBA: { r: 219, g: 219, b: 219, a: 1 },
  SILHOUETTE_VISIBILITY_MIN: 0.2,
  SILHOUETTE_SMOOTHING_ALPHA: 0.25,
  SILHOUETTE_HEAD_RADIUS_RATIO: 0.3,
  SILHOUETTE_STROKE_WIDTH_RATIO: 0.5,

  // 가이드 렌더링 설정
  GUIDE_ENABLED: true,
  GUIDE_SHOW_LABELS: false,
  GUIDE_ALIGN_TO_USER: true,
  GUIDE_MIRROR_MODE: false,
  GUIDE_REFERENCE_COLOR: '#3b82f6',
  GUIDE_POINT_OUTLINE_COLOR: '#ffffff',
  GUIDE_LABEL_COLOR: '#3b82f6',
  GUIDE_LINE_WIDTH: 3,
  GUIDE_POINT_RADIUS: 8,
  GUIDE_POINT_OUTLINE_RADIUS: 10,
  GUIDE_POINT_OUTLINE_WIDTH: 2,
  GUIDE_LABEL_FONT_SIZE_PX: 10,
  GUIDE_LABEL_OFFSET_X: 12,
  GUIDE_LABEL_OFFSET_Y: 5,
  GUIDE_ALPHA_ACTIVE: 0.5,
  GUIDE_ALPHA_IDLE: 0.7,
  GUIDE_TOAST_DURATION_MS: 4500,
  GUIDE_DURATION_USE_TIME_PROGRESS: true,
  GUIDE_DURATION_LOOP: true,

  // 정확도 디버그 로그 설정
  DEBUG_ACCURACY_LOG_ENABLED: true,
  DEBUG_ACCURACY_LOG_VERBOSE: false,
  DEBUG_ACCURACY_LOG_INTERVAL_MS: 500,
  DEBUG_GUIDE_PROGRESS_LOG_ENABLED: false,
  DEBUG_GUIDE_PROGRESS_LOG_INTERVAL_MS: 1000,

  // 타이밍 관련 변수들
  TIMER_TICK_MS: 250,
  TIMER_WARNING_SECONDS: 5,
  STEP_TRANSITION_DELAY_MS: 1500,
  REPS_POPUP_MS: 900,
  TARGET_FPS: 8,
  MILLISECONDS_PER_SECOND: 1000,

  // 정확도 역치
  ACCURACY_SCORE_MAX: 100,
  ACCURACY_THRESHOLD_LOW: 10,
  ACCURACY_THRESHOLD_MID: 60,
  SUCCESS_ACCURACY_THRESHOLD: DURATION_MATCH_THRESHOLD,
  DEFAULT_PROGRESS_RATIO: 0,
  DEFAULT_PHASE: 'undefined',
  REPS_RESET_PHASE: 'start',
  DURATION_ACCUMULATE_ON_FAILURE: true,

  ACCURACY_INPUT_MIRROR_MODE: true,

  // 캐릭터 레벨 업 임계치
  CHARACTER_LEVEL_EXP_THRESHOLD: 1000,
} as const;
