export const NOTIFICATIONS_CONFIG = {
  PAGE_LIMIT: 10,
  INFINITE_SCROLL_ROOT_MARGIN: '200px',
  REFETCH_ON_WINDOW_FOCUS: false,
  REFETCH_ON_RECONNECT: false,
  REFETCH_ON_MOUNT: false,
} as const;
